mkdir /data/genome_tsv
mkdir /data/roadmap_25_imputed
mkdir /data/roadmap_18_status
mkdir /data/roadmap_15_status
mkdir /data/custom_tsv
printf "\n1) Genome_dist"
bedtools sort -i /data/db_gwas/ensembl_gene_hg19.bed.gz | bedtools closest -d -a /data/candidate_1197.bed -b stdin > /data/genome_tsv/nearest_gene.tsv
bedtools sort -i /data/db_gwas/wgEncodeRegTfbsClusteredWithCellsV3.bed.gz | bedtools closest -d -a /data/candidate_1197.bed -b stdin > /data/genome_tsv/encode_tfbs.tsv
bedtools sort -i /data/db_gwas/ucsc_annot.bed.gz | bedtools closest -d -a /data/candidate_1197.bed -b stdin > /data/genome_tsv/ucsc_annot.tsv
printf " 2) Roadmap_dist_15_status"
bedtools sort -i /data/db_gwas/roadmap_15_bed/E001_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E001_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E002_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E002_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E003_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E003_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E004_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E004_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E005_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E005_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E006_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E006_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E007_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E007_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E008_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E008_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E009_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E009_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E010_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E010_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E011_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E011_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E012_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E012_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E013_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E013_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E014_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E014_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E015_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E015_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E016_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E016_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E017_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E017_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E018_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E018_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E019_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E019_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E020_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E020_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E021_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E021_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E022_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E022_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E023_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E023_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E024_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E024_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E025_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E025_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E026_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E026_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E027_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E027_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E028_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E028_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E029_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E029_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E030_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E030_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E031_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E031_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E032_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E032_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E033_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E033_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E034_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E034_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E035_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E035_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E036_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E036_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E037_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E037_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E038_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E038_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E039_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E039_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E040_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E040_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E041_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E041_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E042_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E042_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E043_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E043_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E044_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E044_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E045_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E045_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E046_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E046_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E047_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E047_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E048_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E048_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E049_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E049_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E050_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E050_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E051_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E051_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E052_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E052_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E053_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E053_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E054_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E054_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E055_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E055_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E056_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E056_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E057_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E057_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E058_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E058_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E059_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E059_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E061_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E061_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E062_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E062_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E063_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E063_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E065_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E065_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E066_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E066_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E067_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E067_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E068_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E068_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E069_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E069_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E070_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E070_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E071_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E071_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E072_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E072_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E073_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E073_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E074_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E074_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E075_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E075_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E076_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E076_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E077_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E077_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E078_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E078_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E079_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E079_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E080_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E080_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E081_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E081_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E082_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E082_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E083_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E083_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E084_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E084_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E085_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E085_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E086_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E086_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E087_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E087_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E088_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E088_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E089_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E089_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E090_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E090_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E091_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E091_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E092_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E092_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E093_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E093_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E094_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E094_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E095_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E095_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E096_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E096_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E097_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E097_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E098_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E098_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E099_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E099_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E100_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E100_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E101_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E101_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E102_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E102_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E103_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E103_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E104_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E104_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E105_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E105_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E106_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E106_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E107_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E107_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E108_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E108_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E109_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E109_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E110_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E110_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E111_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E111_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E112_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E112_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E113_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E113_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E114_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E114_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E115_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E115_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E116_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E116_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E117_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E117_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E118_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E118_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E119_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E119_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E120_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E120_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E121_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E121_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E122_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E122_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E123_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E123_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E124_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E124_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E125_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E125_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E126_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E126_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E127_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E127_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E128_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E128_15_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_15_bed/E129_15_coreMarks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_15_status/roadmap_E129_15_state_bed.tsv
printf " 3) Roadmap_dist_18_status"
bedtools sort -i /data/db_gwas/roadmap_18_bed/E003_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E003_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E004_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E004_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E005_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E005_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E006_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E006_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E007_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E007_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E008_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E008_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E011_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E011_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E012_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E012_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E013_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E013_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E014_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E014_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E015_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E015_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E016_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E016_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E017_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E017_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E019_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E019_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E020_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E020_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E021_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E021_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E022_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E022_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E026_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E026_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E029_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E029_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E032_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E032_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E034_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E034_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E037_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E037_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E038_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E038_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E039_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E039_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E040_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E040_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E041_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E041_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E042_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E042_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E043_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E043_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E044_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E044_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E045_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E045_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E046_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E046_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E047_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E047_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E048_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E048_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E049_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E049_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E050_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E050_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E055_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E055_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E056_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E056_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E058_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E058_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E059_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E059_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E061_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E061_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E062_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E062_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E063_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E063_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E065_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E065_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E066_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E066_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E067_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E067_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E068_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E068_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E069_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E069_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E071_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E071_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E072_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E072_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E073_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E073_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E074_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E074_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E075_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E075_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E076_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E076_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E078_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E078_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E079_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E079_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E080_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E080_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E084_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E084_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E085_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E085_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E087_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E087_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E089_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E089_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E090_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E090_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E091_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E091_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E092_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E092_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E093_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E093_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E094_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E094_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E095_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E095_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E096_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E096_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E097_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E097_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E098_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E098_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E099_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E099_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E100_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E100_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E101_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E101_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E102_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E102_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E103_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E103_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E104_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E104_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E105_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E105_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E106_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E106_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E108_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E108_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E109_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E109_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E111_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E111_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E112_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E112_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E113_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E113_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E114_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E114_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E115_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E115_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E116_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E116_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E117_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E117_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E118_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E118_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E119_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E119_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E120_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E120_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E121_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E121_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E122_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E122_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E123_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E123_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E124_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E124_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E125_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E125_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E126_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E126_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E127_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E127_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E128_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E128_18_state_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_18_bed/E129_18_core_K27ac_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_18_status/roadmap_E129_18_state_bed.tsv
printf " 4) Roadmap_dist_25_imputed"
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E001_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E001_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E002_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E002_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E003_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E003_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E004_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E004_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E005_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E005_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E006_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E006_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E007_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E007_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E008_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E008_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E009_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E009_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E010_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E010_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E011_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E011_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E012_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E012_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E013_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E013_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E014_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E014_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E015_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E015_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E016_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E016_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E017_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E017_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E018_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E018_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E019_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E019_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E020_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E020_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E021_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E021_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E022_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E022_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E023_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E023_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E024_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E024_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E025_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E025_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E026_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E026_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E027_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E027_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E028_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E028_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E029_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E029_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E030_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E030_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E031_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E031_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E032_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E032_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E033_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E033_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E034_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E034_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E035_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E035_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E036_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E036_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E037_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E037_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E038_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E038_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E039_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E039_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E040_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E040_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E041_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E041_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E042_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E042_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E043_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E043_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E044_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E044_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E045_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E045_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E046_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E046_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E047_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E047_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E048_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E048_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E049_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E049_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E050_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E050_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E051_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E051_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E052_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E052_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E053_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E053_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E054_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E054_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E055_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E055_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E056_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E056_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E057_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E057_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E058_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E058_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E059_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E059_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E061_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E061_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E062_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E062_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E063_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E063_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E065_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E065_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E066_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E066_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E067_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E067_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E068_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E068_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E069_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E069_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E070_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E070_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E071_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E071_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E072_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E072_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E073_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E073_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E074_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E074_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E075_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E075_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E076_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E076_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E077_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E077_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E078_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E078_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E079_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E079_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E080_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E080_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E081_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E081_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E082_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E082_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E083_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E083_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E084_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E084_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E085_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E085_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E086_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E086_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E087_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E087_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E088_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E088_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E089_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E089_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E090_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E090_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E091_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E091_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E092_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E092_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E093_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E093_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E094_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E094_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E095_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E095_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E096_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E096_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E097_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E097_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E098_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E098_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E099_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E099_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E100_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E100_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E101_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E101_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E102_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E102_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E103_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E103_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E104_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E104_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E105_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E105_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E106_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E106_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E107_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E107_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E108_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E108_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E109_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E109_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E110_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E110_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E111_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E111_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E112_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E112_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E113_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E113_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E114_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E114_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E115_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E115_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E116_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E116_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E117_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E117_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E118_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E118_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E119_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E119_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E120_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E120_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E121_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E121_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E122_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E122_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E123_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E123_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E124_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E124_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E125_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E125_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E126_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E126_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E127_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E127_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E128_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E128_25_imputed_bed.tsv
bedtools sort -i /data/db_gwas/roadmap_25_imputed_bed/E129_25_imputed12marks_dense.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/roadmap_25_imputed/roadmap_E129_25_imputed_bed.tsv
printf " 5) Custom_dist"
bedtools sort -i /data/db_gwas/custom_bed/Corces-Cicero_anchor_hg19lift.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/custom_tsv/Corces-Cicero_anchor_hg19lift.bed.tsv
bedtools sort -i /data/db_gwas/custom_bed/Corces-HiChIP-anchor_hg19lift.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/custom_tsv/Corces-HiChIP-anchor_hg19lift.bed.tsv
bedtools sort -i /data/db_gwas/custom_bed/Corces-scATAC_brain_6_cell-type_hg19lift.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/custom_tsv/Corces-scATAC_brain_6_cell-type_hg19lift.bed.tsv
bedtools sort -i /data/db_gwas/custom_bed/Nott_interactome_anchor_hg19.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/custom_tsv/Nott_interactome_anchor_hg19.bed.tsv
bedtools sort -i /data/db_gwas/custom_bed/Nott_pro_enh_sup_enh_hg19.bed.gz | bedtools intersect -wa -wb -a /data/candidate_1197.bed -b stdin > /data/custom_tsv/Nott_pro_enh_sup_enh_hg19.bed.tsv
